name: actions-sharepoint-upload
description: Upload files to SharePoint
author: INVIXO
branding:
  color: green
  icon: cloud-drizzle
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  site_url:
    description: 'site_url'
    required: true
  client_id:
    description: 'client_id'
    required: true
  client_secret:
    description: 'client_secret'
    required: true
  relative_url:
    description: 'relative_url'
    required: true
  glob:
    description: 'glob'
    required: true